# Generated by Django 4.2.5 on 2023-09-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcategories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttableimages',
            name='level',
        ),
        migrations.RemoveField(
            model_name='projecttableimages',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='projecttableimages',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='projecttableimages',
            name='tree_id',
        ),
    ]
