# Generated by Django 4.2.5 on 2023-09-15 12:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projecttableimages_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
