# Generated by Django 4.2.5 on 2023-09-17 17:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategories',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Proekt', 'verbose_name_plural': 'Proektlar'},
        ),
        migrations.AlterField(
            model_name='projecttableimages',
            name='project',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_table_images', to='projects.projects'),
        ),
    ]
