# Generated by Django 3.2.13 on 2023-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.IntegerField()),
                ('online_yozish', models.CharField(max_length=500)),
                ('instagram', models.URLField()),
                ('whatsapp', models.URLField()),
            ],
        ),
    ]
